server:
  port: 8761

spring:
  application:
    name: commerce

  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: test
    password: test

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

