server:
  port: 8761

spring:
  application:
    name: commerce
  datasource:
    url: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    renewal-threshold-update-interval-ms: 60000 # 임계값 업데이트 간격 (기본값: 15분)
    eviction-interval-timer-in-ms: 60000 # 인스턴스 만료 검사 간격 (기본값: 60초)
